BEGIN;

CREATE TABLE IF NOT EXISTS apiKey (
  id int NOT NULL AUTO_INCREMENT,
  displayName varchar(255) NOT NULL,
  apikey varchar(255) NOT NULL,
  expDate timestamp(6) NULL DEFAULT NULL,
  createdAt timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deletedAt timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

COMMIT;